### ISSUE TITLE
no key found

### ISSUE THREAD

**Issue by willyprayogo26** [thetminko/sgverifyjs#170]
Hi,
I try using your library
but I got stuck like error below:
```
Error occured while getting token [no key found] undefined
ERROR callback: Error: no key found
    at processSig (/Users/xxxxx/web-singpass-service/node_modules/node-jose/lib/jws/verify.js:132:22)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Do you know what's the issue?
Thank you

**Comment by thetminko** [comment]
Have u registered ur app in SGVerify developer portal and downloaded their public cert? Can double check the value of myInfoPublicCert when u init the SgVerifyConnector instance. It should tally with the cert you downloaded.

**Comment by willyprayogo26** [comment]
ok, thanks for your information
I use myInfoPublicCert now, but I still got another error:
```
ERROR callback: Error: "{\"code\":401,\"message\":\"Bearer token check failed.\"}"
    at Function.fetch (/Users/xxxxx/web-singpass-service/node_modules/sgverifyjs/src/util/ApiUtil.ts:60:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at MyInfo.getPersonData (/Users/xxxxx/web-singpass-service/node_modules/sgverifyjs/src/lib/MyInfo/MyInfo.ts:174:18)
    at SingpassVerifyService.getPersonDataInfo (/Users/xxxxx/web-singpass-service/src/singpass-verify/singpass-verify.service.ts:34:12)
    at AppController.callback (/Users/xxxxx/web-singpass-service/src/app.controller.ts:104:26)
    at /Users/xxxxx/web-singpass-service/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at /Users/xxxxx/web-singpass-service/node_modules/@nestjs/core/router/router-proxy.js:9:17
```

Do u know what the issue?
Sorry I asking in here, since singpass/myinfo side is not help much
thanks

**Comment by thetminko** [comment]
Looks like the bearer token is invalid. Can double check the SSL private key, clientId, clientSecret are correct. The personal data attributes that you are requesting through API must exactly match with what you requested during the SGVerify onboarding (compare with the values from the portal and ur code)
